services:
  - mongodb

language: php
sudo: false

php:
  - 5.6

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
    - php: 7.1.3
      env: SYMFONY_VERSION=4.0.* DISABLE_MONGODB=true


before_install:
  - phpenv config-add travis.php.ini
  - if [ "$DISABLE_MONGODB" != "true" ];  then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
  - composer install --prefer-dist --no-interaction --ignore-platform-reqs

script:
  - bin/test
